# Tiltfile

# Build the manager image
# We use the same image name as in the kustomize config (controller:latest)
# Tilt will automatically replace this with a tagged image in the local registry
docker_build(
    'controller:latest',
    '.',
    dockerfile='Dockerfile',
    ignore=['bin', 'cover.out', 'test', 'hack'],
)

# Generate manifests using kustomize
# We use the 'config/default' directory which includes CRDs, RBAC, and the Manager
k8s_yaml(kustomize('config/default'))

# Manage the deployment
# The name matches the Deployment name generated by kustomize (namePrefix + deployment name)
k8s_resource(
    'cashu-operator-controller-manager',
    new_name='manager',
    labels=['operator'],
    # We can add port forwards if needed, e.g., for metrics or webhooks
    # port_forwards=['8080:8080'],
)

# Watch for changes in the API definitions and regenerate code/manifests
local_resource(
    'codegen',
    cmd='make manifests generate',
    deps=['api', 'hack'],
    ignore=['bin', 'cover.out'],
)
