apiVersion: v1
kind: Namespace
metadata:
  annotations:
    meta.helm.sh/release-name: peerpods
    meta.helm.sh/release-namespace: confidential-containers-system
  labels:
    app.kubernetes.io/managed-by: Helm
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: confidential-containers-system
spec:
  finalizers:
  - kubernetes

---
apiVersion: v1
kind: Namespace
metadata:
  labels: {}
  name: coco-tenant
spec:
  finalizers:
  - kubernetes
