apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cc-operator-manager-role
rules:
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - confidentialcontainers.org
  resources:
  - ccruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - confidentialcontainers.org
  resources:
  - ccruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - confidentialcontainers.org
  resources:
  - ccruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cc-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cc-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peerpod-editor
rules:
- apiGroups:
  - confidentialcontainers.org
  resources:
  - peerpods
  verbs:
  - create
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cc-operator-katadeploy-nfd
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeaturerules
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
