apiVersion: mint.cashu.asmogo.github.io/v1alpha1
kind: CashuMint
metadata:
  name: cashumint-postgres
spec:
  image: ghcr.io/cashubtc/cdk-mintd:v0.15.0
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
    runAsNonRoot: true

  # Override container security context
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
  mintInfo:
    url: https://postgres-mint.example.com
    mnemonicSecretRef:
      name: cashumint-postgres-secrets
      key: mnemonic
  database:
    engine: postgres
    postgres:
      autoProvision: true
      tlsMode: disable
      autoProvisionSpec:
        storageSize: 5Gi
        version: "16"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
  paymentBackend:
    fakeWallet:
      supportedUnits:
        - sat
  ingress:
    enabled: true
    host: postgres-mint.example.com
    tls:
      enabled: true
      certManager:
        enabled: true
        issuerName: letsencrypt-prod
