apiVersion: mint.cashu.asmogo.github.io/v1alpha1
kind: CashuMint
metadata:
  name: cashumint-postgres
spec:
  image: asmogo/mintd:sha-e573e43-amd64
  podSecurityContext:
    runAsUser: 0
    fsGroup: 0
    runAsNonRoot: false

  # Override container security context
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: false
    capabilities:
      drop:
        - ALL
  mintInfo:
    url: https://postgres-mint.example.com
    mnemonicSecretRef:
      name: cashumint-postgres-secrets
      key: mnemonic
  database:
    engine: postgres
    postgres:
      autoProvision: true
      tlsMode: disable
      autoProvisionSpec:
        storageSize: 5Gi
        version: "16"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
  lightning:
    backend: fakewallet
    fakeWallet:
      supportedUnits:
        - sat
  ingress:
    enabled: true
    host: postgres-mint.example.com
    tls:
      enabled: true
      certManager:
        enabled: true
        issuerName: letsencrypt-prod