# Minimal CashuMint for testing (requires the referenced Secret in the same namespace)
apiVersion: mint.cashu.asmogo.github.io/v1alpha1
kind: CashuMint
metadata:
  name: cashumint-minimal
spec:
  image: ghcr.io/cashubtc/cdk-mintd:v0.15.0
  podSecurityContext:
    runAsUser: 0
    fsGroup: 0
    runAsNonRoot: false

  # Override container security context
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: false
    capabilities:
      drop:
        - ALL
  mintInfo:
    url: http://cashu.dev.ucash.space
  database:
    engine: sqlite
    sqlite:
      dataDir: /data
  storage:
    size: 5Gi
  lightning:
    backend: fakewallet
    fakeWallet:
      supportedUnits:
        - sat
