//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	if in.MintMaxBat != nil {
		in, out := &in.MintMaxBat, &out.MintMaxBat
		*out = new(int32)
		**out = **in
	}
	if in.EnabledMint != nil {
		in, out := &in.EnabledMint, &out.EnabledMint
		*out = new(bool)
		**out = **in
	}
	if in.EnabledMelt != nil {
		in, out := &in.EnabledMelt, &out.EnabledMelt
		*out = new(bool)
		**out = **in
	}
	if in.EnabledSwap != nil {
		in, out := &in.EnabledSwap, &out.EnabledSwap
		*out = new(bool)
		**out = **in
	}
	if in.EnabledCheckMintQuote != nil {
		in, out := &in.EnabledCheckMintQuote, &out.EnabledCheckMintQuote
		*out = new(bool)
		**out = **in
	}
	if in.EnabledCheckMeltQuote != nil {
		in, out := &in.EnabledCheckMeltQuote, &out.EnabledCheckMeltQuote
		*out = new(bool)
		**out = **in
	}
	if in.EnabledRestore != nil {
		in, out := &in.EnabledRestore, &out.EnabledRestore
		*out = new(bool)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(AuthDatabaseConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDatabaseConfig) DeepCopyInto(out *AuthDatabaseConfig) {
	*out = *in
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDatabaseConfig.
func (in *AuthDatabaseConfig) DeepCopy() *AuthDatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(AuthDatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinRPCConfig) DeepCopyInto(out *BitcoinRPCConfig) {
	*out = *in
	in.UserSecretRef.DeepCopyInto(&out.UserSecretRef)
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinRPCConfig.
func (in *BitcoinRPCConfig) DeepCopy() *BitcoinRPCConfig {
	if in == nil {
		return nil
	}
	out := new(BitcoinRPCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLNConfig) DeepCopyInto(out *CLNConfig) {
	*out = *in
	if in.FeePercent != nil {
		in, out := &in.FeePercent, &out.FeePercent
		*out = new(float64)
		**out = **in
	}
	if in.ReserveFeeMin != nil {
		in, out := &in.ReserveFeeMin, &out.ReserveFeeMin
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLNConfig.
func (in *CLNConfig) DeepCopy() *CLNConfig {
	if in == nil {
		return nil
	}
	out := new(CLNConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashuMint) DeepCopyInto(out *CashuMint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashuMint.
func (in *CashuMint) DeepCopy() *CashuMint {
	if in == nil {
		return nil
	}
	out := new(CashuMint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CashuMint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashuMintList) DeepCopyInto(out *CashuMintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CashuMint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashuMintList.
func (in *CashuMintList) DeepCopy() *CashuMintList {
	if in == nil {
		return nil
	}
	out := new(CashuMintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CashuMintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashuMintSpec) DeepCopyInto(out *CashuMintSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.MintInfo.DeepCopyInto(&out.MintInfo)
	in.Database.DeepCopyInto(&out.Database)
	in.Lightning.DeepCopyInto(&out.Lightning)
	if in.LDKNode != nil {
		in, out := &in.LDKNode, &out.LDKNode
		*out = new(LDKNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPCache != nil {
		in, out := &in.HTTPCache, &out.HTTPCache
		*out = new(HTTPCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagementRPC != nil {
		in, out := &in.ManagementRPC, &out.ManagementRPC
		*out = new(ManagementRPCConfig)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashuMintSpec.
func (in *CashuMintSpec) DeepCopy() *CashuMintSpec {
	if in == nil {
		return nil
	}
	out := new(CashuMintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashuMintStatus) DeepCopyInto(out *CashuMintStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.DatabaseStatus.DeepCopyInto(&out.DatabaseStatus)
	in.LightningStatus.DeepCopyInto(&out.LightningStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashuMintStatus.
func (in *CashuMintStatus) DeepCopy() *CashuMintStatus {
	if in == nil {
		return nil
	}
	out := new(CashuMintStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerConfig) DeepCopyInto(out *CertManagerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerConfig.
func (in *CertManagerConfig) DeepCopy() *CertManagerConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SQLite != nil {
		in, out := &in.SQLite, &out.SQLite
		*out = new(SQLiteConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStatus.
func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeWalletConfig) DeepCopyInto(out *FakeWalletConfig) {
	*out = *in
	if in.SupportedUnits != nil {
		in, out := &in.SupportedUnits, &out.SupportedUnits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FeePercent != nil {
		in, out := &in.FeePercent, &out.FeePercent
		*out = new(float64)
		**out = **in
	}
	if in.ReserveFeeMin != nil {
		in, out := &in.ReserveFeeMin, &out.ReserveFeeMin
		*out = new(int32)
		**out = **in
	}
	if in.MinDelayTime != nil {
		in, out := &in.MinDelayTime, &out.MinDelayTime
		*out = new(int32)
		**out = **in
	}
	if in.MaxDelayTime != nil {
		in, out := &in.MaxDelayTime, &out.MaxDelayTime
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeWalletConfig.
func (in *FakeWalletConfig) DeepCopy() *FakeWalletConfig {
	if in == nil {
		return nil
	}
	out := new(FakeWalletConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCProcessorConfig) DeepCopyInto(out *GRPCProcessorConfig) {
	*out = *in
	if in.SupportedUnits != nil {
		in, out := &in.SupportedUnits, &out.SupportedUnits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCProcessorConfig.
func (in *GRPCProcessorConfig) DeepCopy() *GRPCProcessorConfig {
	if in == nil {
		return nil
	}
	out := new(GRPCProcessorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPCacheConfig) DeepCopyInto(out *HTTPCacheConfig) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int32)
		**out = **in
	}
	if in.TTI != nil {
		in, out := &in.TTI, &out.TTI
		*out = new(int32)
		**out = **in
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(RedisCacheConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPCacheConfig.
func (in *HTTPCacheConfig) DeepCopy() *HTTPCacheConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressConfig) DeepCopyInto(out *IngressConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(IngressTLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressConfig.
func (in *IngressConfig) DeepCopy() *IngressConfig {
	if in == nil {
		return nil
	}
	out := new(IngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTLSConfig) DeepCopyInto(out *IngressTLSConfig) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTLSConfig.
func (in *IngressTLSConfig) DeepCopy() *IngressTLSConfig {
	if in == nil {
		return nil
	}
	out := new(IngressTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDKNodeConfig) DeepCopyInto(out *LDKNodeConfig) {
	*out = *in
	if in.FeePercent != nil {
		in, out := &in.FeePercent, &out.FeePercent
		*out = new(float64)
		**out = **in
	}
	if in.ReserveFeeMin != nil {
		in, out := &in.ReserveFeeMin, &out.ReserveFeeMin
		*out = new(int32)
		**out = **in
	}
	if in.BitcoinRPC != nil {
		in, out := &in.BitcoinRPC, &out.BitcoinRPC
		*out = new(BitcoinRPCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AnnounceAddresses != nil {
		in, out := &in.AnnounceAddresses, &out.AnnounceAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDKNodeConfig.
func (in *LDKNodeConfig) DeepCopy() *LDKNodeConfig {
	if in == nil {
		return nil
	}
	out := new(LDKNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LNBitsConfig) DeepCopyInto(out *LNBitsConfig) {
	*out = *in
	in.AdminAPIKeySecretRef.DeepCopyInto(&out.AdminAPIKeySecretRef)
	in.InvoiceAPIKeySecretRef.DeepCopyInto(&out.InvoiceAPIKeySecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LNBitsConfig.
func (in *LNBitsConfig) DeepCopy() *LNBitsConfig {
	if in == nil {
		return nil
	}
	out := new(LNBitsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LNDConfig) DeepCopyInto(out *LNDConfig) {
	*out = *in
	if in.MacaroonSecretRef != nil {
		in, out := &in.MacaroonSecretRef, &out.MacaroonSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CertSecretRef != nil {
		in, out := &in.CertSecretRef, &out.CertSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FeePercent != nil {
		in, out := &in.FeePercent, &out.FeePercent
		*out = new(float64)
		**out = **in
	}
	if in.ReserveFeeMin != nil {
		in, out := &in.ReserveFeeMin, &out.ReserveFeeMin
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LNDConfig.
func (in *LNDConfig) DeepCopy() *LNDConfig {
	if in == nil {
		return nil
	}
	out := new(LNDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightningConfig) DeepCopyInto(out *LightningConfig) {
	*out = *in
	if in.MinMint != nil {
		in, out := &in.MinMint, &out.MinMint
		*out = new(int64)
		**out = **in
	}
	if in.MaxMint != nil {
		in, out := &in.MaxMint, &out.MaxMint
		*out = new(int64)
		**out = **in
	}
	if in.MinMelt != nil {
		in, out := &in.MinMelt, &out.MinMelt
		*out = new(int64)
		**out = **in
	}
	if in.MaxMelt != nil {
		in, out := &in.MaxMelt, &out.MaxMelt
		*out = new(int64)
		**out = **in
	}
	if in.LND != nil {
		in, out := &in.LND, &out.LND
		*out = new(LNDConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CLN != nil {
		in, out := &in.CLN, &out.CLN
		*out = new(CLNConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LNBits != nil {
		in, out := &in.LNBits, &out.LNBits
		*out = new(LNBitsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FakeWallet != nil {
		in, out := &in.FakeWallet, &out.FakeWallet
		*out = new(FakeWalletConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPCProcessor != nil {
		in, out := &in.GRPCProcessor, &out.GRPCProcessor
		*out = new(GRPCProcessorConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightningConfig.
func (in *LightningConfig) DeepCopy() *LightningConfig {
	if in == nil {
		return nil
	}
	out := new(LightningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightningStatus) DeepCopyInto(out *LightningStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightningStatus.
func (in *LightningStatus) DeepCopy() *LightningStatus {
	if in == nil {
		return nil
	}
	out := new(LightningStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementRPCConfig) DeepCopyInto(out *ManagementRPCConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementRPCConfig.
func (in *ManagementRPCConfig) DeepCopy() *ManagementRPCConfig {
	if in == nil {
		return nil
	}
	out := new(ManagementRPCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MintInfo) DeepCopyInto(out *MintInfo) {
	*out = *in
	if in.MnemonicSecretRef != nil {
		in, out := &in.MnemonicSecretRef, &out.MnemonicSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.InputFeePPK != nil {
		in, out := &in.InputFeePPK, &out.InputFeePPK
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MintInfo.
func (in *MintInfo) DeepCopy() *MintInfo {
	if in == nil {
		return nil
	}
	out := new(MintInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresAutoProvisionSpec) DeepCopyInto(out *PostgresAutoProvisionSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresAutoProvisionSpec.
func (in *PostgresAutoProvisionSpec) DeepCopy() *PostgresAutoProvisionSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresAutoProvisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresConfig) DeepCopyInto(out *PostgresConfig) {
	*out = *in
	if in.URLSecretRef != nil {
		in, out := &in.URLSecretRef, &out.URLSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxConnections != nil {
		in, out := &in.MaxConnections, &out.MaxConnections
		*out = new(int32)
		**out = **in
	}
	if in.ConnectionTimeoutSeconds != nil {
		in, out := &in.ConnectionTimeoutSeconds, &out.ConnectionTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AutoProvisionSpec != nil {
		in, out := &in.AutoProvisionSpec, &out.AutoProvisionSpec
		*out = new(PostgresAutoProvisionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresConfig.
func (in *PostgresConfig) DeepCopy() *PostgresConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisCacheConfig) DeepCopyInto(out *RedisCacheConfig) {
	*out = *in
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisCacheConfig.
func (in *RedisCacheConfig) DeepCopy() *RedisCacheConfig {
	if in == nil {
		return nil
	}
	out := new(RedisCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLiteConfig) DeepCopyInto(out *SQLiteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLiteConfig.
func (in *SQLiteConfig) DeepCopy() *SQLiteConfig {
	if in == nil {
		return nil
	}
	out := new(SQLiteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}
